name: Run blank.py check and Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Run blank.py script
      run: |
        python blank.py > output.txt
        if grep -q "IlyaTHEbest" output.txt; then
          echo "Test passed: 'IlyaTHEbest' found in output!"
        else
          echo "Test failed: 'IlyaTHEbest' NOT found in output!"
          exit 1
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/blank:latest
